apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jirasoftwares.cloudfitsoftware.com
spec:
  group: cloudfitsoftware.com
  names:
    kind: JiraSoftware
    listKind: JiraSoftwareList
    plural: jirasoftwares
    singular: jirasoftware
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
